import sys, os, concurrent.futures as cf
sys.path.insert(0, '../ep3')
import gen
SHEET = 'refs/sheet_g2.png'
BGSTYLE = ("Japanese anime background art, hand-painted production BG (ufotable / Makoto Shinkai quality), cinematic, painterly but clean, "
           "NO characters, NO text. Palette: deep indigo and blue night, silver moonlight on snow, cyan-tinged shadows.")
J = [
 # ---- backgrounds
 ('bg/BG01_tilt.png', "Tall vertical composition for a camera tilt: at the top a huge bright FULL moon (not eclipsed) in a starry indigo sky with thin clouds; below, the tops of snow-laden pines; at the bottom a quiet snowy clearing seen from a low angle, fresh untouched snow with a few scorch marks and faint drifting orange embers. " + BGSTYLE, [], '1024x1536', None),
 ('bg/BG03_treeline.png', "Close view of the dark edge of a snowy pine forest at night, deep black shadows between the trunks, the snow at the forest edge lit by cold moonlight, eerie fog creeping low. Very dark interior so glowing eyes can appear in it. " + BGSTYLE, [], '1536x1024', None),
 ('bg/BG04_strip.png', "Wide horizontal side-view of a snowy forest clearing at night for a side-scrolling camera pan: flat snowfield across the lower third, a band of pines behind, eclipsed moon with a thin silver ring high in the sky. Seamlessly tileable left-to-right, even composition with no focal point. " + BGSTYLE, [], '1536x1024', None),
 ('bg/BG05_kingsky.png', "Low-angle vertical sky: a vast dark sky drained of color, almost monochrome blue-grey, the moon fully eclipsed into a thin burning silver-white ring high at the top, clouds being drawn upward in a spiral toward it, the tops of pines at the very bottom. " + BGSTYLE, [], '1024x1536', None),
 ('bg/BG06_crater.png', "Top-down view looking straight down into a shallow crater blasted into deep snow at night, cracked compacted snow and ice at the center, rim of thrown snow, falling snowflakes, cold desaturated blue-grey. Empty — no people. " + BGSTYLE, [], '1536x1024', None),
 ('bg/BG07_flank.png', "Abstract vertical texture of the flank of a colossal monster made of living black shadow: dense layered jagged spikes of black fur sweeping downward, dozens of small glowing cyan slit eyes scattered through it, smoke wisps, lit from below by hot orange and magenta firelight. Seamlessly tileable top-to-bottom. Anime background art, no text.", [], '1024x1536', None),
 ('bg/BG08_apex.png', "Anime background art: a black night sky dominated by a gigantic eclipsed sun/moon — a black disk with a blazing corona ring of white-gold light and streaming magenta and orange flares radiating outward, sparks and embers floating everywhere. Epic, awe-inspiring, centered. No characters, no text.", [], '1536x1024', None),
 ('bg/BG09_dawn.png', "Anime background art: sunrise over a snowy mountain forest seen from a snowy ridge, the sun just rising at the horizon on the left, sky graded from violet at the top to rose pink to warm gold, sun rays, burnt and charred pines in the middle distance, glowing embers drifting down like snow. Hopeful, gorgeous. No characters, no text.", [], '1536x1024', None),
 ('bg/BG10_night_low.png', "Anime background art: extreme low angle from snow level in a snowy clearing at night looking up at a huge eclipsed moon ring in the sky, tall black pine silhouettes framing the edges, snow crystals glittering in the foreground. No characters, no text. " + BGSTYLE, [], '1536x1024', None),
 # ---- props / creatures
 ('props/KING.png', "Anime key visual element on a transparent background: the head and shoulders of a colossal wolf-shaped god made of living black shadow, seen from the front and slightly below, towering. A crown of broken black spikes, huge ears, a ruff of jagged shadow fur, dozens of small glowing cyan eyes scattered across its brow and cheeks plus two huge slanted main eyes, a long muzzle, faint cyan rim light on its edges, black smoke streaming off it. Flat anime cel shading, pure black body with one dark blue shadow tone. No text.", ['../ep3/refs/king_keyvisual_v1.png'], '1536x1024', 'transparent'),
 ('props/PAW.png', "Anime cel drawing on a transparent background: a gigantic clawed paw of a shadow monster seen from directly below as it comes down toward the viewer, extreme foreshortening, five huge pale claws, black shadow fur with cyan rim light, smoke trailing. Flat cel shading, no text.", ['../ep3/refs/wolf_sheet_v1.png'], '1024x1024', 'transparent'),
 ('props/CLASP.png', "Anime extreme close-up key frame, full frame: an orange diamond-shaped crystal clasp pinned on crimson cloth at the collar of a cloak, a charcoal scarf edge, the crystal cracked and dim with a faint dying ember glow deep inside, a single snowflake resting on it. Cel-shaded with painterly glow. No text.", [SHEET], '1536x1024', None),
 ('props/CLASP_lit.png', "The same anime extreme close-up of the orange diamond crystal clasp on crimson cloth, but now the crystal blazes with brilliant white-gold fire from within, light bursting through the crack, embers flying off it, the cloth lit orange. Cel-shaded with painterly glow. No text.", [SHEET], '1536x1024', None),
 ('props/WEAPON_sheet.png', "Anime prop settei (model sheet) on white: a large folding gun-scythe: (1) fully deployed side view, (2) folded compact, (3) dynamic three-quarter view. Matte black shaft with thin red stripes, a compact rifle receiver and barrel at the top of the shaft, a wide curved steel blade whose edge has a faint orange line, visible hinge. Clean line art, flat cel colors. No text.", ['../ep3/refs/weapon_sheet_v1.png', 'keys/C3_extend.png'], '1536x1024', None),
 ('props/WOLF_cycle.png', "Anime animation model sheet on a transparent background: a 6-drawing gallop cycle of the same shadow wolf running to the RIGHT, drawn in a single row left to right, evenly spaced, identical size and design in every drawing: contact, collect, push, extended flight, reach, land. Pure black body with spiky torn-shadow mane, glowing cyan slit eyes, faint cyan rim light, smoke wisps. Flat cel style, no text, no grid lines.", ['keys/W1_leap.png'], '1536x1024', 'transparent'),
 # ---- FX cels
 ('fx/FX_ink.png', "Japanese anime hand-drawn EFFECTS animation sheet on a transparent background: 6 sequential drawings of a black ink explosion (monster disintegrating), in a 3 by 2 grid, evenly spaced: small dense splash, bursting splash with flying droplets, large jagged burst with shards, breaking apart, scattering droplets and wisps, last fading wisps. Pure black ink with cyan glinting edges, bold anime FX style (like Yutaka Nakamura / Bones effects). No text, no grid lines.", [], '1536x1024', 'transparent'),
 ('fx/FX_fire.png', "Japanese anime hand-drawn EFFECTS animation sheet on a transparent background: 6 sequential drawings of a stylized fire burst, 3 by 2 grid evenly spaced: spark, flare, big flame burst, flames licking outward, breaking into tongues, dissipating embers. Graphic anime fire in layered shapes: hot white-yellow core, orange, magenta-pink outer edges, sharp geometric flame tongues (Promare / TRIGGER style). No text, no grid lines.", [], '1536x1024', 'transparent'),
 ('fx/FX_snow.png', "Japanese anime hand-drawn EFFECTS animation sheet on a transparent background: 6 sequential drawings of a snow impact burst kicked up from the ground, 3 by 2 grid evenly spaced: initial spray, rising plume, big billowing cloud, spreading, thinning, last drifting flakes. Anime-style cel-shaded snow clouds, white with pale blue shadow shapes and crisp outlines. No text, no grid lines.", [], '1536x1024', 'transparent'),
 ('fx/FX_slash.png', "Japanese anime hand-drawn EFFECTS sheet on a transparent background: 6 different sharp sword-slash impact effects, 3 by 2 grid: crescent slash arcs, cross flash, radiating impact star, shattered light shards. Pure white and pale gold light with a thin orange edge, bold graphic anime style. No text, no grid lines.", [], '1536x1024', 'transparent'),
 ('fx/FX_wing.png', "Anime hand-drawn EFFECTS element on a transparent background: one huge phoenix wing made of stylized fire, feathers as sharp geometric flame blades fanning outward, hot white-yellow at the root, orange, magenta-pink at the tips (Promare / TRIGGER fire). Seen from the front, the root at the lower left. No text.", [], '1536x1024', 'transparent'),
]
def run(j):
    out, p, refs, size, bg = j
    if os.path.exists(out): return 'skip ' + out
    try: return gen.oai_image(p, out, refs=refs, model='gpt-image-2', size=size, quality='high', background=bg, note='ep4 ' + out)
    except BaseException as e: return f'FAIL {out} {str(e)[:200]}'
with cf.ThreadPoolExecutor(6) as ex:
    for r in ex.map(run, J): print(r, flush=True)
